/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef _heavyflavordiffpdf_cxx_
#define _heavyflavordiffpdf_cxx_

#if !defined(__CINT__) || defined(__MAKECINT__)

#include <math.h> 
#include "TMath.h" 
#include "Riostream.h" 

#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#endif
 
class HeavyFlavorDiffPDF : public RooAbsPdf {
public:
  HeavyFlavorDiffPDF() { setCategory(1); } ; 
  HeavyFlavorDiffPDF(const char *name, const char *title,
		 RooAbsReal& _bmult,
		 RooAbsReal& _r,
		 RooAbsReal& _eb1, RooAbsReal& _eb2,
		 RooAbsReal& _eq1, RooAbsReal& _eq2,
		 RooAbsReal& _fcorrect,
		 RooAbsReal& _fttbar,
		 RooAbsReal& _fsingletop,
		 RooAbsReal& _catocc);
  
  HeavyFlavorDiffPDF(const HeavyFlavorDiffPDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new HeavyFlavorDiffPDF(*this,newname); }
  inline virtual ~HeavyFlavorDiffPDF() { }

  void setCategory(int _icat)  { icat=_icat; }

protected:

  RooRealProxy bmult ;
  RooRealProxy r ;
  RooRealProxy eb1,eb2 ;
  RooRealProxy eq1,eq2 ;
  RooRealProxy fcorrect;
  RooRealProxy fttbar;
  RooRealProxy fsingletop;
  RooRealProxy catocc;
  Int_t icat;

  Double_t evaluate() const ;
  Double_t _evaluate(int nBtags) const;
  Double_t _evaluateKernel(int nMisassignments, int nBtags, bool doNorm=true) const;
  Double_t _normalizedAcceptance(Double_t R) const;
  
private:

  ClassDef(HeavyFlavorDiffPDF,1) // Your description goes here...
};
 
#endif
